### ISSUE TITLE
Extra parenthesis added when none expected

### ISSUE THREAD

**Issue by vwong** [marko-js/prettier#1]
## Version

1.1.0

### Details

Extra parentheses added when none expected, causing an invalid syntax.

### Expected Behavior

It does not create an invalid syntax.

### Actual Behavior

It creates an invalid syntax, and is not idempotent.

### Your Environment

Node 16.8.0
Linux

### Steps to Reproduce

Write this code. And run `prettier`.

Ignore the senseless body, it's just to get it long enough, so prettier doesn't make it a single line. The bug happens even with short bodies.

```
<macro name="recursive">
  <await(generator.next())>
    <@then|{ value, done }|>
      <div>
        <ul><li>${value}</li></ul>
        <ul><li>${value}</li></ul>
        <ul><li>${value}</li></ul>
      </div>
    </@then>
  </await>
</macro>
```

Notice it gets transformed to (the extra parentheses added).
```
<macro name="recursive">
  <await(generator.next())>
    <@then|({ value, done })|>
      <div>
        <ul><li>${value}</li></ul>
        <ul><li>${value}</li></ul>
        <ul><li>${value}</li></ul>
      </div>
    </@then>
  </await>
</macro>
```

Which is invalid code. Indeed, re-running prettier a second time, indicates it as much.

**Comment by DylanPiercey** [comment]
Thanks for taking the time to create the issue @vwong. Let me know if anything else comes up!
