### ISSUE TITLE
Honour existing class attribute syntax

### ISSUE THREAD

**Issue by ianmcburnie** [marko-js/prettier#18]
### Description

<img width="230" alt="Screen Shot 2023-03-09 at 11 30 05 AM" src="https://user-images.githubusercontent.com/38065/224141665-c6ae6569-d841-4e29-9e9b-8274f937aa27.png">

Plugin is changing existing html class formatting to shorthand syntax.

We should honor existing format and/or make it configurable.

**Comment by eugef** [comment]
Hi @DylanPiercey, would be great to have this issue fixed as it is the main blocker for us to adopt this module.

**Comment by eugef** [comment]
I can confirm that issue is fixed

**Comment by ianmcburnie** [comment]
Thanks for the quick turnaround!
