### ISSUE TITLE
Camel cased attribute tags transform to lowercase

### ISSUE THREAD

**Issue by stephenscaff** [marko-js/prettier#4]
### Details

Not sure if this is a bug with `prettier-plugin-marko` or a behavior with `prettier`. Hoping you can provide some insight.

When I run prettier on a `.marko` file, custom attribute tags with camel casing are transformed to lowercase. 

For example, say you have a layout component with body content denoting page header and content regions.

```
// components/app-layout/index.marko

<${input.pageHeader}/>
<${input.pageContent}/>
```

And then you use those attribute tags in a page template:

```
// components/pages/somepage/index.marko

<@pageHeader>
<header></header>
</@pageHeader>

<@pageContent>
<section></section>
</@pageContent>
```

After running prettier, those camel cased attributes will become lowercase:

```
<@pageheader>
<header></header>
</@pageheader>

<@pagecontent>
<section></section>
</@pagecontent>
```

### Expected Behavior

Text casing of the attribute tags would persist when running prettier.

### Actual Behavior

Camel cased attributes transform to lowercase.

### Possible Fix

No idea. Not sure if the issue is with this plugin or prettier. I read that Prettier normalizes the case of case insensitive stuff in HTML. So it that could be the cause. But I couldn't replicate the issue using the Prettier playground (granted not at all one to one).

If that is the issue, I'd hope there would be an override for marko files that prevented transforming the text case.

<details><summary>Additional Info</summary>

### Your Environment

- VS CODE
- Build using marko 5.17.5`, @marko/vite 2.2.0, @marko/compiler 5.15.4, @marko/express.

### Steps to Reproduce

1.  Use body tags with lower camel cased naming: ie: `<${input.pageContent}/>`
2.  Use the came cased attribute tags in a page template: `<@pageContent></@pageContent>
3. Run prettier with prettier-plugin-marko, either via VSCode page formating (Shift + Opt + F on Mac), OR via CLI `npm exec -- prettier --write "src/pages/somepage.marko"`

If need be I can provide a reduced test. And of course, I could just _not_ use camelCased attribute tags.

</details>

Thanks!

**Comment by DylanPiercey** [comment]
@stephenscaff this was an oversight, Marko tag names are case sensitive in general but it looks like we're `toLowerCase`ing it here. Will get out a patch shortly.
