### ISSUE TITLE
Self closing tags are not being formatted correctly

### ISSUE THREAD

**Issue by Jonaphant** [marko-js/prettier#49]
## Version: x.x.x
`prettier-plugin-marko@3.0.1`

### Details

When formatting with prettier, self closing tags are not being formatted the same as components that have open/closing tags.

### Expected Behavior

```
    <@column
        field='campaignName'
        columnText='Campaign name'
        columnDescription='Campaign name desc'
        width='1fr'
        align='center'
        sortable=true
    />

    <@column
        field='clicks'
        columnText='Clicks'
        columnDescription='Clicks desc'
        width='1fr'
        align='right'
        sortable=true
    />
```

### Actual Behavior

```

    <@column field='campaignName' columnText='Campaign name' columnDescription='Campaign name desc'
    width='1fr' align='center' sortable=true /> <@column field='clicks' columnText='Clicks'
    columnDescription='Clicks desc' width='1fr' align='right' sortable=true />

```

### Possible Fix

<details><summary>Additional Info</summary>

### Your Environment

- Environment name and version (e.g. Chrome 39, node.js 5.4):
- Operating System and version (desktop or mobile):
- Link to your project:

### Steps to Reproduce

1.  first...
2.
3.
4.

### Stack Trace

</details>

**Comment by DylanPiercey** [comment]
Should be fixed
